services:
  - type: web
    name: naimbif
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "NAIMbif - Ladang Bridlot"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:YVfDpakeFLsXPGzPjwyH3UWbwglTFLrImnnWFwhiZ60=
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://naimbif.onrender.com
      - key: APP_TIMEZONE
        value: Asia/Kuala_Lumpur
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
